name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test suite
    # List of supported runners:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-22.04

    env:
      COMPOSE_PROJECT_NAME: docker-elk

    steps:
      - uses: actions/checkout@v4

      - name: Pre-build container images
        run: >-
          docker compose
          -f docker-compose.yml
          build

      - name:  Run the stack
        run: |
          docker compose up setup
          docker compose up -d

      - name: Terminate all components
        if: always()
        run: >-
          docker compose
          -f docker-compose.yml
          down -v
