name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    name: Test suite
    # List of supported runners:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    runs-on: ubuntu-22.04

    env:
      COMPOSE_PROJECT_NAME: docker-elk

    steps:
      - uses: actions/checkout@v4

      #####################################################
      #                                                   #
      # Install all dependencies required by test suites. #
      #                                                   #
      #####################################################

      - name: Pre-build container images
        run: >-
          docker compose
          -f docker-compose.yml
          build

      ########################################################
      #                                                      #
      # Ensure ยง"Initial setup" of the README remains valid. #
      #                                                      #
      ########################################################

      - name: Set password of every built-in user to 'testpasswd'
        run: |

          sed -i -e 's/\(ELASTIC_PASSWORD=\)'\''changeme'\''/\1testpasswd/g' \
                 -e 's/\(KIBANA_SYSTEM_PASSWORD=\)'\''changeme'\''/\1testpasswd/g' \

      ##########################################################
      #                                                        #
      # Test core components: Elasticsearch, Logstash, Kibana. #
      #                                                        #
      ##########################################################

      - name:  Run the stack
        run: |
          docker compose up setup
          docker compose up -d

      # Elasticsearch's high disk watermark gets regularly exceeded on GitHub Actions runners.
      # https://www.elastic.co/guide/en/elasticsearch/reference/8.10/fix-watermark-errors.html
      - name: Disable Elasticsearch disk allocation decider
        run: .github/workflows/scripts/disable-disk-alloc-decider.sh

      - name: Execute core test suite
        run: .github/workflows/scripts/run-tests-core.sh

      - name: Terminate all components
        if: always()
        run: >-
          docker compose
          -f docker-compose.yml
          down -v
